TT#22828 Adapt to handle ndb.up scripts - WIP, untested
Change-Id: I21e20fca42a00217eab0ecdfe9e1c11046f11e33

diff --git a/ngcp-update-ndbcluster-schema b/ngcp-update-ndbcluster-schema
--- a/ngcp-update-ndbcluster-schema
+++ b/ngcp-update-ndbcluster-schema
@@ -7,58 +7,44 @@ verbose() {
   fi
 }
 
-usage() {
-  echo -e "Usage: $0 [OPTION]..." 1>&2
-  echo -e "\t-f: Force update, even if running on active node" 1>&2
-}
-
-FORCE_ACTIVE_NODE=false
-RUN_SYNC_DB=false
-SYNC_DB="/usr/sbin/ngcp-sync-db"
 NOT_REPLICATED_REV_APPLIED=false
-
-while getopts "fh" opt; do
-    case "${opt}" in
-        f)
-            FORCE_ACTIVE_NODE=true
-            ;;
-        h)
-            usage; exit 0;
-            ;;
-        *)
-            usage; exit 1;
-            ;;
-    esac
-done
-shift $((OPTIND-1))
-
 nodename=$(/usr/sbin/ngcp-nodename 2>/dev/null || echo "unknown")
 if [ "${nodename}" = "unknown" ] ; then
   echo "Error: nodename could not be identified." >&2
   exit 1
 fi
 
-/etc/init.d/mysql start || true
 . /etc/mysql/sipwise.cnf
-
 . /etc/default/ngcp-roles
+. /etc/default/ngcp-db
+
+NDB_PORT="$CLUSTER_DBPORT"
+NDB_HOST="$CLUSTER_DBHOST"
 
 if [ -z "${SIPWISE_DB_PASSWORD}" ] ; then
   echo 'Error: SIPWISE_DB_PASSWORD is unset (using /etc/mysql/sipwise.cnf).' >&2
   exit 1
 fi
 
-# check connection with sipwise user
-if ! mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" -e 'SELECT 1;' 1>/dev/null 2>/dev/null ; then
-  echo 'Error: cant connect to local MySQL with sipwise user' >&2
-  exit 1
+if [ -z "${NDB_PORT}" ]; then
+  verbose 'Not a proxy or db, nothing to do...';
+  exit
 fi
+
+if ! $NGCP_NDB; then
+    echo "Error: NDB not enabled" >&2
+    exit 1
+fi
+
+/etc/init.d/mysql start 3 || true
+
+sqlargs=(-usipwise -p"${SIPWISE_DB_PASSWORD}" -h"${NDB_HOST}" -P"${NDB_PORT}")
 
 # support automated installation
 if [ -n "$AUTOMATED_INSTALL_MODE" ] ; then
   echo "Running in automated installation mode, ignoring check for empty db_schema."
 else
-  if [ "$(mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" -e 'select * from ngcp.db_schema;' 2>/dev/null)" = "" ] ; then
+  if [ "$(mysql "${sqlargs[@]}" -e 'select * from ngcp.db_schema;' 2>/dev/null)" = "" ] ; then
     echo "================================================================="
     echo "Warning: the db_schema table of the ngcp database is empty."
     echo "Are you sure you want to proceed with applying db-schema changes?"
@@ -74,50 +60,13 @@ else
   fi
 fi
 
-if ! mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" -e 'use ngcp;' 2>/dev/null ; then
+if ! mysql "${sqlargs[@]}" -e 'use ngcp;' 2>/dev/null ; then
   mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" < /usr/share/ngcp-db-schema/db_scripts/init/0005_create_ngcp.up
+  echo 'Error: NDB ngcp database does not exit.' >&2
 fi
-
-if ! mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" -e 'use ngcp;' 2>/dev/null ; then
-  echo 'Error: ngcp database does not exist.' >&2
+if ! mysql "${sqlargs[@]}" ngcp -e 'describe db_schema'  >/dev/null; then
+  echo 'Error: NDB db_schema table does not exit.' >&2
   exit 1
-fi
-
-if ! mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" ngcp -e 'describe db_schema'  >/dev/null; then
-  echo 'Error: db_schema table does not exit.' >&2
-  exit 1
-fi
-
-if [ -z "$SKIP_SYNC_DB" ] && [ "$NGCP_TYPE" = "carrier" ] && [ "$NGCP_IS_PROXY" = "yes" ] ; then
-  if ! $FORCE_ACTIVE_NODE && [ ! -x "$SYNC_DB" ] ; then
-    echo "Error: ${SYNC_DB} is required for carrier proxy (or lacking execute permissions)." >&2
-    exit 1
-  fi
-  RUN_SYNC_DB=true
-fi
-
-running_on_active_node() {
-  if [ "$nodename" = "spce" ] ; then
-    return 1
-  else
-    if /usr/sbin/ngcp-check_active -q ; then
-      if $FORCE_ACTIVE_NODE; then
-        echo "Force update on active node as requested."
-      else
-        echo "This seems to be the active node, nothing to do."
-      fi
-      return 0
-    else
-      echo "This seems to be the inactive node, applying revisions."
-      return 1
-    fi
-  fi
-}
-
-if running_on_active_node ; then
-  ACTIVE_NODE=true
-else
-  ACTIVE_NODE=false
 fi
 
 apply_revision() {
@@ -127,7 +76,7 @@ apply_revision() {
   revname="$(basename "$rev")"
 
   printf "Applying revision script %s: " "$rev"
-  if mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" < "$rev" ; then
+  if mysql "${sqlargs[@]}" < "$rev" ; then
     echo "done"
   else
     echo "failed. :(" >&2
@@ -135,7 +84,7 @@ apply_revision() {
     exit 1
   fi
 
-  if mysql -usipwise -p"${SIPWISE_DB_PASSWORD}" ngcp -e "insert into db_schema values (0, '${revname}', '${nodename}', CURRENT_TIMESTAMP);" ; then
+  if mysql "${sqlargs[@]}" ngcp -e "insert into db_schema values (0, '${revname}', '${nodename}', CURRENT_TIMESTAMP);" ; then
     verbose "Marked revision $rev as applied."
   else
     echo "Error while executing DB commands using revision $rev for node $nodename" >&2
@@ -147,12 +96,13 @@ apply_revision() {
 apply_revs() {
   [ -n "$1" ] || return 1
 
-  revs="$1"
+  local revs="$1"
+  local node_revs
 
   # generate list of rev scripts that are node specific, used inside
   # missing_revision's ngcp-check-rev-applied ... --node $nodename
   for rev in $revs ; do
-    revision_file="$(find /usr/share/ngcp-db-schema/db_scripts -name "$rev")"
+    revision_file="$(find /usr/share/ngcp-db-schema/ndb_scripts -name "$rev")"
 
     case "$revision_file" in
       *_not_replicated.up)
@@ -164,15 +114,24 @@ apply_revs() {
   # shellcheck disable=SC2086
   for missing_revision in \
     $( {
-        ngcp-check-rev-applied --schema db_schema --revision $revs                         | awk '/^No match for revision/ {print $5}' ;
-        ngcp-check-rev-applied --schema db_schema --revision $node_revs --node "$nodename" | awk '/^No match for revision/ {print $5}' ;
+        ngcp-check-rev-applied --schema db_schema \
+            --dbhost "$NDB_HOST" --dbport "$NDB_PORT" \
+            --revision $revs \
+            | awk '/^No match for revision/ {print $5}' ;
+        ngcp-check-rev-applied --schema db_schema \
+            --dbhost "$NDB_HOST" --dbport "$NDB_PORT" \
+            --revision $node_revs --node "$nodename" \
+            | awk '/^No match for revision/ {print $5}' ;
        } | sort -n -u ) ; do
-    revision_file="$(find /usr/share/ngcp-db-schema/db_scripts -name "$missing_revision")"
+    revision_file="$(find /usr/share/ngcp-db-schema/ndb_scripts -name "$missing_revision")"
 
     # execute the rev script if there's no entry for the *current* host yet
     case "$revision_file" in
       *_not_replicated.up)
-        if ngcp-check-rev-applied --schema db_schema --revision "$missing_revision" --node "$nodename" | grep -q 'already executed' ; then
+        if ngcp-check-rev-applied --schema db_schema \
+            --dbhost "$NDB_HOST" --dbport "$NDB_PORT" \
+            --revision "$missing_revision" --node "$nodename" \
+            | grep -q 'already executed' ; then
           continue
         fi
         ;;
@@ -233,34 +192,14 @@ revision_wrapper() {
 }
 
 # make sure we get sorted 10XXX after 9XXX
-cd /usr/share/ngcp-db-schema/db_scripts/base/
+cd /usr/share/ngcp-db-schema/ndb_scripts/base/
 # shellcheck disable=SC2035 disable=SC2046
 revision_wrapper $(printf '%s\0' *.up | sort -z -n | while IFS= read -r -d "" file; do \
-                   echo "/usr/share/ngcp-db-schema/db_scripts/base/$file"; done)
+                   echo "/usr/share/ngcp-db-schema/ndb_scripts/base/$file"; done)
 
-cd /usr/share/ngcp-db-schema/db_scripts/diff/
+cd /usr/share/ngcp-db-schema/ndb_scripts/diff/
 # shellcheck disable=SC2035 disable=SC2046
 revision_wrapper $(printf '%s\0' *.up | sort -z -n | while IFS= read -r -d "" file; do \
-                   echo "/usr/share/ngcp-db-schema/db_scripts/diff/$file"; done)
-
-# for carrier prx* hosts sync master-slave replication for not_replicated statements (if any)
-if $RUN_SYNC_DB && ($NOT_REPLICATED_REV_APPLIED || [ -n "$AUTOMATED_INSTALL_MODE" ]); then
-  if [ -x "$SYNC_DB" ] ; then
-      PRX_SYNC_DBS="billing carrier kamailio provisioning prosody mysql"
-      EXTRA_SYNC_DB_OPTS=""
-      if [ -n "$AUTOMATED_INSTALL_MODE" ] ; then
-          EXTRA_SYNC_DB_OPTS="--local-user=root --init-replication --set-local-grants"
-      fi
-      # shellcheck disable=SC2086
-      if /usr/sbin/ngcp-sync-db --verbose --force --use-central-db --repl-mode "master-slave" --databases "${PRX_SYNC_DBS}" --ssh-tunnel=33125 ${EXTRA_SYNC_DB_OPTS}; then
-          echo "Syncing 'not_replicated' statements from the central node."
-      else
-          echo "Error: While syncing 'not_replicated' statements from the central node, please run ngcp-sync-db-wrapper manually to fix them." >&2
-          exit 1
-      fi
-  else
-      echo "Warning: Skipping sync of 'not_replicated' statements from the central node as ${SYNC_DB} is missing on the current node." >&2
-  fi
-fi
+                   echo "/usr/share/ngcp-db-schema/ndb_scripts/diff/$file"; done)
 
 ## END OF FILE #################################################################
