Error out if a sript can not be read
Never happened so far but better safe than sorry...

From: Michael Prokop <mprokop@sipwise.com>

diff --git a/ngcp-update-db-schema b/ngcp-update-db-schema
--- a/ngcp-update-db-schema
+++ b/ngcp-update-db-schema
@@ -141,6 +141,11 @@ revision_wrapper() {
 
   for rev in $* ; do
 
+    if ! [ -r "$rev" ] ; then
+      echo "Error: $rev can not be read." >&2
+      exit 1
+    fi
+
     cd $(dirname $rev) || exit 1 # would fail if a script references a file (like language_strings.txt) in its CWD
 
     revname="$(basename $rev)"
